/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // All colors reference CSS variables so dark mode works by switching :root values
        'primary':                    'rgb(var(--clr-primary) / <alpha-value>)',
        'on-primary':                 'rgb(var(--clr-on-primary) / <alpha-value>)',
        'secondary':                  'rgb(var(--clr-secondary) / <alpha-value>)',
        'on-secondary':               'rgb(var(--clr-on-secondary) / <alpha-value>)',
        'surface':                    'rgb(var(--clr-surface) / <alpha-value>)',
        'on-surface':                 'rgb(var(--clr-on-surface) / <alpha-value>)',
        'on-surface-variant':         'rgb(var(--clr-on-surface-variant) / <alpha-value>)',
        'surface-container-lowest':   'rgb(var(--clr-surface-container-lowest) / <alpha-value>)',
        'surface-container-low':      'rgb(var(--clr-surface-container-low) / <alpha-value>)',
        'surface-container':          'rgb(var(--clr-surface-container) / <alpha-value>)',
        'surface-container-high':     'rgb(var(--clr-surface-container-high) / <alpha-value>)',
        'surface-container-highest':  'rgb(var(--clr-surface-container-highest) / <alpha-value>)',
        'surface-bright':             'rgb(var(--clr-surface-bright) / <alpha-value>)',
        'surface-dim':                'rgb(var(--clr-surface-dim) / <alpha-value>)',
        'outline':                    'rgb(var(--clr-outline) / <alpha-value>)',
        'outline-variant':            'rgb(var(--clr-outline-variant) / <alpha-value>)',
        // Static colors that don't change with theme
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'surface-variant':            '#e3e2e2',
        'surface-tint':               '#5e5e5e',
        'inverse-surface':            '#303031',
        'inverse-on-surface':         '#f2f0f0',
        'inverse-primary':            '#c6c6c6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max-width': '1200px',
        'margin-mobile':  '24px',
        'margin-desktop': '64px',
        'stack-sm':  '16px',
        'stack-md':  '32px',
        'stack-lg':  '80px',
        'gutter':    '32px',
        'unit':      '8px',
      },
      fontFamily: {
        'display-lg':        ['Poppins', 'sans-serif'],
        'display-lg-mobile': ['Poppins', 'sans-serif'],
        'headline-lg':       ['Poppins', 'sans-serif'],
        'headline-md':       ['Poppins', 'sans-serif'],
        'body-lg':           ['Roboto', 'sans-serif'],
        'body-md':           ['Roboto', 'sans-serif'],
        'label-md':          ['Roboto', 'sans-serif'],
        'label-sm':          ['Roboto', 'sans-serif'],
      },
      fontSize: {
        'display-lg':        ['64px',  { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['40px',  { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg':       ['32px',  { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md':       ['24px',  { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg':           ['18px',  { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':           ['16px',  { lineHeight: '1.6', fontWeight: '400' }],
        'label-md':          ['14px',  { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm':          ['12px',  { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
